#
# Turn this into a basic template for HARP

# Site settings
title: RRFSS Data Explorer
description: Make data beautiful with Jekyll
baseurl: "/RRFSS-data-explorer"
url: "https://durhamregionharp.github.io"

# User settings
username: Durham Region HARP
user_description: Epidemiologists making data fun again
user_title: Health Analytics Research and Policy
email: EEPilot@durham.ca
facebook_username: durhamregionhealth
twitter_username: durhamepis
github_username: DurhamRegionHARP

# Build settings
markdown: kramdown
